
[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.1.0"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/gddo"

[[constraint]]
  name = "github.com/jjeffery/errors"
  version = "1.0.1"

[prune]
  go-tests = true
  unused-packages = true
